repos:
- repo: https://github.com/grantjenks/blue
  rev: v0.9.1
  hooks:
    - id: blue
      language_version: python3.10
- repo: https://github.com/john-hen/Flake8-pyproject
  rev: 0.9.1
  hooks:
    - id: Flake8-pyproject
      language_version: python3.10
- repo: https://github.com/pycqa/isort
  rev: 5.12.0 # an isort release exposing the hook
  hooks:
    - id: isort
      name: isort (python)
- repo: https://github.com/pdm-project/pdm
  rev: 2.8.2 # a PDM release exposing the hook
  hooks:
    - id: pdm-lock-check
      always_run: true
- repo: local
  hooks:
    - id: pytest-check
      name: pytest-check
      entry: pdm pytest
      language: system
      pass_filenames: false
      always_run: true
